### PR TITLE
Bumped scalac, sbt, scalaz versions

### PR DESCRIPTION
**Pull request by 2chilled**
Fixed some scalaz-issues in addition

### CODE REVIEW

**Comment by 2chilled** [comment]
Fails because of org.scalaz#scalaz-core_2.9.2;7.1.3: not found. Do you really want to further support Scala 2.9.2?

**Comment by chris-twiner** [comment]
No, I think it's safe to drop support now thanks :-D

**Comment by 2chilled** [comment]
@chris-twiner ping

**Comment by 2chilled** [comment]
Nice to see that you're still alive. I really like your library. We use it quite extensively in production for almost a year now without any issues. Since there has been not that much activity during 2015, do you have any plans for further development and maintenance? For myself, I hope I can find time to contribute a bit during 2016. Cheers

**Comment by chris-twiner** [comment]
Thanks! Truly cool to hear when it's being used in prod :-D

I do have further plans but its mostly a question of time and energy levels
to be honest.

My job has moved further away from coding in the last year, so I'll need to
invest more to keep my skills sharp anyway :-D

Key things planned are a streams impl, type provider style strategies (use
a schema to optimise memory usage etc ) an xml syntax plugin and string
interpolation.

There is some other compile time stuff I'd like to nail down such as qname
verification etc.

**Comment by aaubert** [comment]
I also have to say that it is a very useful project. My colleagues have a project in production since several months with it and I am currently developing an other project which will be in production in a few days. I am also working on a module to add support for Scales in the http4s project.

Would it be possible to publish soon the 0.6.0-M4 milestone in Maven Central, so that we could get the full compatibility with Scalaz 7.1 ?

And by the way, I would like maybe to contribute a bit to Scales, so if you have ideas of improvements, you may open issues and, if I have time, I will try to work on it.

**Comment by 2chilled** [comment]
@chris-twiner +1 for publishing 0.6.0-M4. We'd love to use the equality API for unit testing, which is impossible atm using scalaz 7.1.

**Pull request merged**
